name: complete
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_ui_auth: ^1.8.0
  firebase_ui_firestore: ^1.5.11
  firebase_ui_oauth: ^1.4.0
  firebase_ui_oauth_google: ^1.0.21
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf