// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOo1bH4XsP7K4Jz76ZTK9Fi7MoYB8mHQ',
    appId: '1:794742218118:web:8252e2c0e8594ddc262007',
    messagingSenderId: '794742218118',
    projectId: 'flutterfire-ui-codelab-e4cbb',
    authDomain: 'flutterfire-ui-codelab-e4cbb.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-e4cbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvZlbCCxphT-uVBQ3JYykLv5rgU3-zbE0',
    appId: '1:794742218118:android:439bb4c779a669be262007',
    messagingSenderId: '794742218118',
    projectId: 'flutterfire-ui-codelab-e4cbb',
    storageBucket: 'flutterfire-ui-codelab-e4cbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzCTQdt1pSElSKwHG0WJI1meW_YfYEbGw',
    appId: '1:794742218118:ios:7a0806c336377e33262007',
    messagingSenderId: '794742218118',
    projectId: 'flutterfire-ui-codelab-e4cbb',
    storageBucket: 'flutterfire-ui-codelab-e4cbb.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzCTQdt1pSElSKwHG0WJI1meW_YfYEbGw',
    appId: '1:794742218118:ios:e03e5215a01ea4d7262007',
    messagingSenderId: '794742218118',
    projectId: 'flutterfire-ui-codelab-e4cbb',
    storageBucket: 'flutterfire-ui-codelab-e4cbb.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
